insert into public.fish_species (id, name, scientific_name, image_name, habitat, rarity_stars, is_rare, about)
values
  (1, 'Albacore', 'Profile pending', 'MysteryFish', 'Offshore', 1, false, null),
  (2, 'Amberjack', 'Profile pending', 'MysteryFish', 'Offshore', 1, false, null),
  (3, 'Atlantic Salmon', 'Profile pending', 'MysteryFish', 'Coastal', 1, false, null),
  (4, 'Australian Bass', 'Profile pending', 'MysteryFish', 'River', 1, false, null),
  (5, 'Australian Salmon', 'Profile pending', 'AustralianSalmon', 'Surf beach', 1, false, null),
  (6, 'Australian Sawtail', 'Profile pending', 'MysteryFish', 'Reef', 1, false, null),
  (7, 'Balmain Bug', 'Profile pending', 'MysteryFish', 'Sand flats', 1, false, null),
  (8, 'Banded Rock Cod (Bar Cod)', 'Profile pending', 'MysteryFish', 'Reef', 1, false, null),
  (9, 'Bass Groper', 'Profile pending', 'MysteryFish', 'Deep reef', 1, false, null),
  (10, 'Brook Trout', 'Profile pending', 'MysteryFish', 'Highland stream', 1, false, null),
  (11, 'Brown Trout', 'Profile pending', 'MysteryFish', 'Highland stream', 1, false, null),
  (12, 'Beach Worm', 'Profile pending', 'MysteryFish', 'Surf beach', 1, false, null),
  (13, 'Bigeye Tuna', 'Profile pending', 'MysteryFish', 'Offshore', 1, false, null),
  (14, 'Black Bream', 'Profile pending', 'MysteryFish', 'Estuary', 1, false, null),
  (15, 'Blacklip Abalone', 'Profile pending', 'MysteryFish', 'Rock reef', 1, false, null),
  (16, 'Blue-eye Trevalla', 'Profile pending', 'MysteryFish', 'Deep reef', 1, true, null),
  (17, 'Blue Groper', 'Profile pending', 'MysteryFish', 'Rock reef', 1, false, null),
  (18, 'Blue Swimmer Crab', 'Profile pending', 'MysteryFish', 'Bay', 1, false, null),
  (19, 'Bluefish', 'Profile pending', 'MysteryFish', 'Surf beach', 1, false, null),
  (20, 'Bonito', 'Profile pending', 'MysteryFish', 'Coastal', 1, false, null),
  (21, 'Carp', 'Profile pending', 'MysteryFish', 'River', 1, false, null),
  (22, 'Cobia', 'Profile pending', 'MysteryFish', 'Offshore', 1, false, null),
  (23, 'Cockles', 'Profile pending', 'MysteryFish', 'Sand flats', 1, false, null),
  (24, 'Commercial Scallop', 'Profile pending', 'MysteryFish', 'Bay', 1, false, null),
  (25, 'Cunjevoi', 'Profile pending', 'MysteryFish', 'Rock reef', 1, false, null),
  (26, 'Cuttlefish', 'Profile pending', 'MysteryFish', 'Reef', 1, false, null),
  (27, 'Eastern Red Scorpionfish (Red Rock Cod)', 'Profile pending', 'MysteryFish', 'Rock reef', 1, false, null),
  (28, 'Eastern Rock Lobster', 'Profile pending', 'MysteryFish', 'Rock reef', 1, false, null),
  (29, 'Eastern School Whiting', 'Profile pending', 'MysteryFish', 'Sand flats', 1, false, null),
  (30, 'Eels (Short and Long-finned)', 'Profile pending', 'ShortFinnedEel', 'River', 1, false, null),
  (31, 'Estuary Perch', 'Profile pending', 'MysteryFish', 'Estuary', 1, false, null),
  (32, 'Flathead (Bluespotted)', 'Profile pending', 'MysteryFish', 'Sand flats', 1, false, null),
  (33, 'Flathead (Dusky)', 'Profile pending', 'MysteryFish', 'Estuary', 1, false, null),
  (34, 'Flathead (Tiger)', 'Profile pending', 'MysteryFish', 'Sand flats', 1, false, null),
  (35, 'Flounder', 'Profile pending', 'MysteryFish', 'Sand flats', 1, false, null),
  (36, 'Freshwater Catfish', 'Profile pending', 'MysteryFish', 'River', 1, false, null),
  (37, 'Garfish', 'Profile pending', 'MysteryFish', 'Bay', 1, false, null),
  (38, 'Gemfish', 'Profile pending', 'MysteryFish', 'Deep reef', 1, true, null),
  (39, 'Golden Perch', 'Profile pending', 'MysteryFish', 'River', 1, false, null),
  (40, 'Grey Morwong (Rubber Lip)', 'Profile pending', 'MysteryFish', 'Reef', 1, false, null),
  (41, 'Hairtail', 'Profile pending', 'MysteryFish', 'Estuary', 1, false, null),
  (42, 'Hapuku', 'Profile pending', 'MysteryFish', 'Deep reef', 1, true, null),
  (43, 'Leatherjacket', 'Profile pending', 'MysteryFish', 'Reef', 1, false, null),
  (44, 'Longtail Tuna', 'Profile pending', 'MysteryFish', 'Offshore', 1, false, null),
  (45, 'Luderick', 'Profile pending', 'MysteryFish', 'Rock wash', 1, false, null),
  (46, 'Mackerel (Narrow-barred Spanish)', 'Profile pending', 'MysteryFish', 'Offshore', 1, false, null),
  (47, 'Mackerel (Spotted)', 'Profile pending', 'MysteryFish', 'Offshore', 1, false, null),
  (48, 'Mahi Mahi (Dolphinfish)', 'Profile pending', 'MysteryFish', 'Bluewater', 1, true, null),
  (49, 'Mangrove Jack', 'Profile pending', 'MysteryFish', 'Estuary', 1, false, null),
  (50, 'Marlin (Black)', 'Profile pending', 'MysteryFish', 'Bluewater', 1, true, null),
  (51, 'Marlin (Blue)', 'Profile pending', 'MysteryFish', 'Bluewater', 1, true, null),
  (52, 'Marlin (Striped)', 'Profile pending', 'MysteryFish', 'Bluewater', 1, true, null),
  (53, 'Morwong (Banded)', 'Profile pending', 'MysteryFish', 'Reef', 1, false, null),
  (54, 'Morwong (Jackass)', 'Profile pending', 'MysteryFish', 'Reef', 1, false, null),
  (55, 'Morwong (Red)', 'Profile pending', 'MysteryFish', 'Reef', 1, false, null),
  (56, 'Moses Snapper', 'Profile pending', 'MysteryFish', 'Reef', 1, false, null),
  (57, 'Mud Crab', 'Profile pending', 'MysteryFish', 'Estuary', 1, false, null),
  (58, 'Mullet (Poddy)', 'Profile pending', 'MysteryFish', 'Estuary', 1, false, null),
  (59, 'Mullet (Sea)', 'Profile pending', 'MysteryFish', 'Coastal', 1, false, null),
  (60, 'Mulloway', 'Profile pending', 'MysteryFish', 'Estuary', 1, false, null),
  (61, 'Murray Cod', 'Profile pending', 'MysteryFish', 'River', 1, false, null),
  (62, 'Murray Crayfish', 'Profile pending', 'MysteryFish', 'River', 1, false, null),
  (63, 'Native Oyster', 'Profile pending', 'MysteryFish', 'Estuary', 1, false, null),
  (64, 'Octopus', 'Profile pending', 'MysteryFish', 'Reef', 1, false, null),
  (65, 'Pacific Oyster', 'Profile pending', 'MysteryFish', 'Estuary', 1, false, null),
  (66, 'Pearl Perch', 'Profile pending', 'MysteryFish', 'Reef', 1, false, null),
  (67, 'Prawn - Black Tiger', 'Profile pending', 'MysteryFish', 'Estuary', 1, false, null),
  (68, 'Prawn - School Prawn', 'Profile pending', 'MysteryFish', 'Estuary', 1, false, null),
  (69, 'Purple Sea Urchin', 'Profile pending', 'MysteryFish', 'Reef', 1, false, null),
  (70, 'Rainbow Trout', 'Profile pending', 'MysteryFish', 'Highland stream', 1, false, null),
  (71, 'Redfin Perch', 'Profile pending', 'MysteryFish', 'Lake', 1, false, null),
  (72, 'Rock Blackfish', 'Profile pending', 'MysteryFish', 'Rock wash', 1, false, null),
  (73, 'Sailfish', 'Profile pending', 'MysteryFish', 'Bluewater', 1, true, null),
  (74, 'Samsonfish', 'Profile pending', 'MysteryFish', 'Offshore', 1, false, null),
  (75, 'Sand Whiting', 'Profile pending', 'MysteryFish', 'Sand flats', 1, false, null),
  (76, 'Shark - Blue', 'Profile pending', 'MysteryFish', 'Offshore', 1, false, null),
  (77, 'Shark - Hammerhead', 'Profile pending', 'MysteryFish', 'Offshore', 1, true, null),
  (78, 'Shark - Mako', 'Profile pending', 'MysteryFish', 'Offshore', 1, true, null),
  (79, 'Shark - School', 'Profile pending', 'MysteryFish', 'Offshore', 1, false, null),
  (80, 'Shark - Whaler', 'Profile pending', 'MysteryFish', 'Offshore', 1, false, null),
  (81, 'Shark - Wobbegong', 'Profile pending', 'MysteryFish', 'Reef', 1, false, null),
  (82, 'Shortbill Spearfish', 'Profile pending', 'MysteryFish', 'Bluewater', 1, true, null),
  (83, 'Silver Perch', 'Profile pending', 'MysteryFish', 'River', 1, false, null),
  (84, 'Spiny Crayfish', 'Profile pending', 'MysteryFish', 'River', 1, false, null),
  (85, 'Slipper Lobster', 'Profile pending', 'MysteryFish', 'Reef', 1, false, null),
  (86, 'Snapper', 'Profile pending', 'PinkSnapper', 'Reef', 1, false, null),
  (87, 'Sole', 'Profile pending', 'MysteryFish', 'Sand flats', 1, false, null),
  (88, 'Southern Bluefin Tuna', 'Profile pending', 'MysteryFish', 'Offshore', 1, true, null),
  (89, 'Southern Rock Lobster', 'Profile pending', 'MysteryFish', 'Rock reef', 1, false, null),
  (90, 'Spanner Crab', 'Profile pending', 'MysteryFish', 'Sand flats', 1, false, null),
  (91, 'Squid', 'Profile pending', 'MysteryFish', 'Bay', 1, false, null),
  (92, 'Swordfish', 'Profile pending', 'MysteryFish', 'Bluewater', 1, true, null),
  (93, 'Sydney Rock Oyster', 'Profile pending', 'MysteryFish', 'Estuary', 1, false, null),
  (94, 'Tailor', 'Profile pending', 'MysteryFish', 'Surf beach', 1, false, null),
  (95, 'Tarwhine', 'Profile pending', 'MysteryFish', 'Estuary', 1, false, null),
  (96, 'Teraglin', 'Profile pending', 'MysteryFish', 'Reef', 1, false, null),
  (97, 'Trevallies', 'Profile pending', 'MysteryFish', 'Coastal', 1, false, null),
  (98, 'Tropical Rock Lobster (Painted and Ornate)', 'Profile pending', 'MysteryFish', 'Tropical reef', 1, true, null),
  (99, 'Turban Snails', 'Profile pending', 'MysteryFish', 'Rock reef', 1, false, null),
  (100, 'Wahoo', 'Profile pending', 'MysteryFish', 'Bluewater', 1, true, null),
  (101, 'Yabby', 'Profile pending', 'MysteryFish', 'River', 1, false, null),
  (102, 'Yellowfin Bream', 'Profile pending', 'YellowfinBream', 'Estuary', 1, false, null),
  (103, 'Yellowfin Tuna', 'Profile pending', 'MysteryFish', 'Offshore', 1, false, null)
on conflict (id) do update
set
  name = excluded.name,
  scientific_name = excluded.scientific_name,
  image_name = excluded.image_name,
  habitat = excluded.habitat,
  rarity_stars = excluded.rarity_stars,
  is_rare = excluded.is_rare,
  about = excluded.about;

select setval(pg_get_serial_sequence('public.fish_species', 'id'), 103, true);

insert into public.achievements (id, slug, title, description, sort_order)
values
  (1, 'first_catch', 'First Catch', 'Log your first fish in the dex.', 1),
  (2, 'ten_species', 'Species Spotter', 'Catch 10 unique species.', 2),
  (3, 'rare_finder', 'Rare Finder', 'Catch a rare species.', 3),
  (4, 'master_angler', 'Master Angler', 'Catch 50 unique species.', 4),
  (5, 'legend_status', 'Legendary Status', 'Reach level 50.', 5),
  (6, 'offshore_hunter', 'Offshore Hunter', 'Catch 5 offshore species.', 6),
  (7, 'reef_explorer', 'Reef Explorer', 'Catch 5 reef species.', 7),
  (8, 'river_runner', 'River Runner', 'Catch 5 river species.', 8),
  (9, 'bluewater_king', 'Bluewater King', 'Catch a bluewater trophy.', 9),
  (10, 'weight_warrior', 'Weight Warrior', 'Log 1,000 lbs total catch weight.', 10),
  (11, 'estuary_expert', 'Estuary Expert', 'Catch 5 estuary species.', 11),
  (12, 'coastal_cruiser', 'Coastal Cruiser', 'Catch 5 coastal species.', 12),
  (13, 'night_owl', 'Night Owl', 'Catch a fish after midnight.', 13),
  (14, 'weekend_warrior', 'Weekend Warrior', 'Catch on a Saturday or Sunday.', 14),
  (15, 'dex_completionist', 'Dex Completionist', 'Catch every species in the catalog.', 15)
on conflict (id) do update
set
  slug = excluded.slug,
  title = excluded.title,
  description = excluded.description,
  sort_order = excluded.sort_order;

select setval(pg_get_serial_sequence('public.achievements', 'id'), 15, true);

